# Workflow name
name: "Chromatic"

# Event for the workflow
on:
  push:
    branches:
      - main

# List of jobs
jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/wme-ui
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: pnpm install
        # 👇 Runs yarn in ./packages/wme-ui
        working-directory: packages/wme-ui

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          # 👇 Runs Chromatic CLI in ./packages/wme-ui
          workingDir: packages/wme-ui
          token: ${{ secrets.GITHUB_TOKEN }}
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
